### ISSUE TITLE
StarDisplay 1.19+ seems to be broken on PJ64 2.3+

### ISSUE THREAD

**Issue by YYoshi241** [aglab2/SM64StarDisplay#10]
I'm having the same problem as issue #6, it gets such on 3) Let Star Display Init. This problem doesn't occur on Project64 2.2 or earlier. Version 1.18 and older work correctly.

**Comment by IronYoshi64** [comment]
Use Project64 latest public release 3.0.1 or latest Dev build for latest Star Display to work.

**Comment by aglab2** [comment]
https://github.com/aglab2/SM64StarDisplay/releases/tag/1.21
