### ISSUE TITLE
Antivirus removes StarDisplay upon startup

### ISSUE THREAD

**Issue by yourizuring** [aglab2/SM64StarDisplay#2]
I don't think I can use this program because my antivirus is preventing me from doing so.
Someone please fix this.

**Comment by aglab2** [comment]
Unfortunately, Star Display could be considered as a malicious application by Machine Learning heuristics as it both accceses the Internet to download layouts and reads other processs memory. To surpass this, you need to report Star Display exe on Windows Defender support website:
[Link](https://www.microsoft.com/en-us/wdsi/filesubmission)

You need to find out the "Detection Name" in that Windows Defender have given to the application. On Windows 10 that could be done in Windows Defender Settings > Virus and thread protection > Threat History.

Once Windows Defender support confirmed file is not malicious, you need to clean up Antivrus Cache. I have written a script that does, 
[AVClearCache.zip](https://github.com/aglab2/SM64StarDisplay/files/2916335/AVClearCache.zip) Extract zip file and run bat in it as Administator, could be done by right-clicking on bat file and selecting Run as Administator.

I myself will report Star Display on the Windows Defender support form when false positive reoccur. Please leave comment on this issue if such behaviour happens again.

**Comment by aglab2** [comment]
[AVClearCache.zip](https://github.com/aglab2/SM64StarDisplay/files/2916760/AVClearCache.zip)
Updated AVClearCache script from newer definition.

**Comment by aglab2** [comment]
If Windows Defender still treats application as malware, you can add it to Windows Defender exclusion. Go to Virus & threat protection > Virus & threat protection settings > Exclusions and add the folder containing Star Display.

**Comment by aglab2** [comment]
Did not occur for a lot of time, assume MS fixed
