### ISSUE TITLE
Feature Request: Simulated Keypress on Event

### ISSUE THREAD

**Issue by Jackall4BDN** [aglab2/SM64StarDisplay#5]
While i See that this tool is for casual playthroughs it already came in handy for my speed runs with the auto-delete feature.
However it also would be useful for splits if we could mark certain Stars or Star counts, as well as Flags like Keys etc. for a Manually Configured Keypress event to make splitting a bit more automatic.
Would love to see this, as everything else about this simple app already is incredibly useful.

**Comment by aglab2** [comment]
You may use autosplitter from another repo to perform ths. [https://raw.githubusercontent.com/aglab2/LiveSplitAutoSplitters/master/LiveSplit.SuperMario64.asl](link)
Feature in Star Display to delete file on reset was done when autosplitter did not exist, to implement other feature IPC between LiveSplit and StarDisplay would need to be implemented which is pain
