### ISSUE TITLE
No longer works for newer PJ64 Dev builds

### ISSUE THREAD

**Issue by IronYoshi64** [aglab2/SM64StarDisplay#6]
I really enjoy using this program! It is great to have up when playing SM64 hacks and if you are going for 100% completion!

So the issue is that this program no longer works with the newer Dev builds of Project64, which is not cool.

I have literally downloaded over like 50 PJ64 builds to see when it first stopped working with StarDisplay. I found out that Project64 v2.4.0-660-g7d602ca, which was built on February 19 2018, is the last version that actually works with the program, well at least from my testing. Builds newer than this will never get past the 3) let star display init step.

Here is a screenshot of where it gets stuck on when using newer PJ64 builds:
![stardisplay stuck on 2](https://user-images.githubusercontent.com/57850880/70377639-3e944e80-18dc-11ea-93e6-09aeb3e296ee.png)

I hope this can be fixed later.

**Comment by IronYoshi64** [comment]
Any news about this? I I really hope this can be fixed and updated sometime soon! It will be nice so that Users can enjoy the added benefits of newer builds over the older builds, and be able to fully use this program.

**Comment by aglab2** [comment]
Fixed in new version
