### ISSUE TITLE
Problem with JSML conversion

### ISSUE THREAD

**Issue by DNVIC** [aglab2/SM64StarDisplay#7]
When loading some SML files and saving it as a JSML, the layout becomes unusable. It is no longer possible to distinguish between collected stars and uncollected stars.

Example:
I got a layout file for Shining Stars 1.5, since it currently does not have one in the database, and it worked fine. However, I decided to save it as a JSML in the main folder so I wouldn't have to manually load it every time I restart stardisplay.

Here's what the original SML file looked like:
https://cdn.discordapp.com/attachments/544271316350533633/876776766520303636/unknown.png

Later, I restarted the emulator and stardisplay, and here is what I saw (this is only with saving the file as a JSML):
https://cdn.discordapp.com/attachments/544271316350533633/876777690244448286/unknown.png

I was curious as to whether just saving the file as an SML would cause the same issue, and since (for good reason) its no longer possible to save an SML file, I used an older stardisplay version to load the original SML and just save it. This didn't change anything.
https://cdn.discordapp.com/attachments/544271316350533633/876777723111043072/unknown.png

SML files in question:
https://drive.google.com/file/d/16MQzs1g-CQK9j9wTNR6Ln26iU-eQy0Xr/view?usp=sharing

**Comment by aglab2** [comment]
Nice catch, fixed in 1,14 by using PNG format instead of BMP that does not support translucency,
